import type { DemoCategory, DemoProduct } from './types';

export const DEMO_CATEGORIES: DemoCategory[] = [
  { id: 'CAT-STP', name: 'Staples',        colour: '#f59e0b', imagePath: '/demo/products/staples.svg' },
  { id: 'CAT-BEV', name: 'Beverages',      colour: '#3b82f6', imagePath: '/demo/products/beverages.svg' },
  { id: 'CAT-DAI', name: 'Dairy',          colour: '#06b6d4', imagePath: '/demo/products/dairy.svg' },
  { id: 'CAT-SNK', name: 'Snacks',         colour: '#ef4444', imagePath: '/demo/products/snacks.svg' },
  { id: 'CAT-HOU', name: 'Household',      colour: '#8b5cf6', imagePath: '/demo/products/household.svg' },
  { id: 'CAT-TOI', name: 'Toiletries',     colour: '#ec4899', imagePath: '/demo/products/toiletries.svg' },
  { id: 'CAT-BAB', name: 'Baby & Health',  colour: '#10b981', imagePath: '/demo/products/baby-health.svg' },
  { id: 'CAT-FRZ', name: 'Frozen/Chilled', colour: '#0ea5e9', imagePath: '/demo/products/frozen.svg' },
  { id: 'CAT-LCL', name: 'Local Market',   colour: '#84cc16', imagePath: '/demo/products/local-market.svg' },
  { id: 'CAT-STA', name: 'Stationery',     colour: '#64748b', imagePath: '/demo/products/stationery.svg' },
];

// All monetary values in pesewas (GHS × 100)
export const DEMO_PRODUCTS: DemoProduct[] = [
  // ── STAPLES ──────────────────────────────────────────────────────────────
  { id:'P001', sku:'STP-001', barcode:'DMO0001', name:"Mama's Best Rice 5kg",      categoryId:'CAT-STP', imagePath:'/demo/products/staples.svg',    costPricePence:3200,  sellingPricePence:3900,  openingQty:45, reorderPoint:12, vatRateBps:0,    unit:'bag'    },
  { id:'P002', sku:'STP-002', barcode:'DMO0002', name:'Golden Harvest Rice 10kg',  categoryId:'CAT-STP', imagePath:'/demo/products/staples.svg',    costPricePence:5800,  sellingPricePence:7200,  openingQty:30, reorderPoint:8,  vatRateBps:0,    unit:'bag'    },
  { id:'P003', sku:'STP-003', barcode:'DMO0003', name:'Roller Flour 2kg',          categoryId:'CAT-STP', imagePath:'/demo/products/staples.svg',    costPricePence:1200,  sellingPricePence:1550,  openingQty:55, reorderPoint:15, vatRateBps:0,    unit:'bag'    },
  { id:'P004', sku:'STP-004', barcode:'DMO0004', name:'Panda White Sugar 1kg',     categoryId:'CAT-STP', imagePath:'/demo/products/staples.svg',    costPricePence:700,   sellingPricePence:900,   openingQty:90, reorderPoint:25, vatRateBps:0,    unit:'bag'    },
  { id:'P005', sku:'STP-005', barcode:'DMO0005', name:'Gino Tomato Paste 400g',    categoryId:'CAT-STP', imagePath:'/demo/products/staples.svg',    costPricePence:600,   sellingPricePence:800,   openingQty:75, reorderPoint:20, vatRateBps:0,    unit:'tin'    },
  { id:'P006', sku:'STP-006', barcode:'DMO0006', name:'Frytol Cooking Oil 1L',     categoryId:'CAT-STP', imagePath:'/demo/products/staples.svg',    costPricePence:1800,  sellingPricePence:2300,  openingQty:60, reorderPoint:15, vatRateBps:0,    unit:'bottle' },
  { id:'P007', sku:'STP-007', barcode:'DMO0007', name:'Frytol Cooking Oil 5L',     categoryId:'CAT-STP', imagePath:'/demo/products/staples.svg',    costPricePence:8200,  sellingPricePence:10000, openingQty:22, reorderPoint:5,  vatRateBps:0,    unit:'bottle' },
  { id:'P008', sku:'STP-008', barcode:'DMO0008', name:'Sardines (Titus) 170g',     categoryId:'CAT-STP', imagePath:'/demo/products/staples.svg',    costPricePence:500,   sellingPricePence:650,   openingQty:55, reorderPoint:15, vatRateBps:0,    unit:'tin'    },
  { id:'P009', sku:'STP-009', barcode:'DMO0009', name:'Mackerel Tin 400g',         categoryId:'CAT-STP', imagePath:'/demo/products/staples.svg',    costPricePence:900,   sellingPricePence:1200,  openingQty:38, reorderPoint:10, vatRateBps:0,    unit:'tin'    },
  { id:'P010', sku:'STP-010', barcode:'DMO0010', name:'Dangote Salt 500g',         categoryId:'CAT-STP', imagePath:'/demo/products/staples.svg',    costPricePence:150,   sellingPricePence:200,   openingQty:130,reorderPoint:40, vatRateBps:0,    unit:'pack'   },
  { id:'P011', sku:'STP-011', barcode:'DMO0011', name:'Groundnut Oil 1L',          categoryId:'CAT-STP', imagePath:'/demo/products/staples.svg',    costPricePence:2000,  sellingPricePence:2600,  openingQty:42, reorderPoint:12, vatRateBps:0,    unit:'bottle' },
  { id:'P012', sku:'STP-012', barcode:'DMO0012', name:'Semovita 1kg',              categoryId:'CAT-STP', imagePath:'/demo/products/staples.svg',    costPricePence:900,   sellingPricePence:1150,  openingQty:48, reorderPoint:12, vatRateBps:0,    unit:'pack'   },
  { id:'P013', sku:'STP-013', barcode:'DMO0013', name:'Yam Flour 1kg',             categoryId:'CAT-STP', imagePath:'/demo/products/staples.svg',    costPricePence:1100,  sellingPricePence:1400,  openingQty:38, reorderPoint:10, vatRateBps:0,    unit:'pack'   },
  { id:'P014', sku:'STP-014', barcode:'DMO0014', name:'Gari Fine 1kg',             categoryId:'CAT-STP', imagePath:'/demo/products/staples.svg',    costPricePence:600,   sellingPricePence:800,   openingQty:65, reorderPoint:18, vatRateBps:0,    unit:'bag'    },
  { id:'P015', sku:'STP-015', barcode:'DMO0015', name:'Indomie Noodles (pack of 40)',categoryId:'CAT-STP',imagePath:'/demo/products/staples.svg',   costPricePence:2800,  sellingPricePence:3500,  openingQty:28, reorderPoint:8,  vatRateBps:0,    unit:'pack'   },

  // ── BEVERAGES ─────────────────────────────────────────────────────────────
  { id:'P016', sku:'BEV-001', barcode:'DMO0016', name:'Voltic Water 500ml',        categoryId:'CAT-BEV', imagePath:'/demo/products/beverages.svg', costPricePence:150,   sellingPricePence:200,   openingQty:180,reorderPoint:50, vatRateBps:0,    unit:'bottle' },
  { id:'P017', sku:'BEV-002', barcode:'DMO0017', name:'Voltic Water 1.5L',         categoryId:'CAT-BEV', imagePath:'/demo/products/beverages.svg', costPricePence:300,   sellingPricePence:400,   openingQty:120,reorderPoint:35, vatRateBps:0,    unit:'bottle' },
  { id:'P018', sku:'BEV-003', barcode:'DMO0018', name:'Coca-Cola 500ml',           categoryId:'CAT-BEV', imagePath:'/demo/products/beverages.svg', costPricePence:400,   sellingPricePence:550,   openingQty:100,reorderPoint:30, vatRateBps:0,    unit:'bottle' },
  { id:'P019', sku:'BEV-004', barcode:'DMO0019', name:'Fanta Orange 500ml',        categoryId:'CAT-BEV', imagePath:'/demo/products/beverages.svg', costPricePence:400,   sellingPricePence:550,   openingQty:75, reorderPoint:22, vatRateBps:0,    unit:'bottle' },
  { id:'P020', sku:'BEV-005', barcode:'DMO0020', name:'Sprite 500ml',              categoryId:'CAT-BEV', imagePath:'/demo/products/beverages.svg', costPricePence:400,   sellingPricePence:550,   openingQty:55, reorderPoint:16, vatRateBps:0,    unit:'bottle' },
  { id:'P021', sku:'BEV-006', barcode:'DMO0021', name:'Milo 400g Tin',             categoryId:'CAT-BEV', imagePath:'/demo/products/beverages.svg', costPricePence:2800,  sellingPricePence:3600,  openingQty:35, reorderPoint:10, vatRateBps:0,    unit:'tin'    },
  { id:'P022', sku:'BEV-007', barcode:'DMO0022', name:'Milo Sachet Box (30s)',      categoryId:'CAT-BEV', imagePath:'/demo/products/beverages.svg', costPricePence:1500,  sellingPricePence:2000,  openingQty:28, reorderPoint:8,  vatRateBps:0,    unit:'box'    },
  { id:'P023', sku:'BEV-008', barcode:'DMO0023', name:'Cowbell Milk 400g',         categoryId:'CAT-BEV', imagePath:'/demo/products/beverages.svg', costPricePence:1800,  sellingPricePence:2400,  openingQty:45, reorderPoint:12, vatRateBps:0,    unit:'tin'    },
  { id:'P024', sku:'BEV-009', barcode:'DMO0024', name:'Alvaro Pineapple 330ml',    categoryId:'CAT-BEV', imagePath:'/demo/products/beverages.svg', costPricePence:550,   sellingPricePence:750,   openingQty:55, reorderPoint:16, vatRateBps:0,    unit:'bottle' },
  { id:'P025', sku:'BEV-010', barcode:'DMO0025', name:'Malta Guinness 330ml',      categoryId:'CAT-BEV', imagePath:'/demo/products/beverages.svg', costPricePence:450,   sellingPricePence:600,   openingQty:72, reorderPoint:20, vatRateBps:0,    unit:'bottle' },
  { id:'P026', sku:'BEV-011', barcode:'DMO0026', name:'Kool Juice 500ml',          categoryId:'CAT-BEV', imagePath:'/demo/products/beverages.svg', costPricePence:480,   sellingPricePence:650,   openingQty:65, reorderPoint:18, vatRateBps:0,    unit:'bottle' },
  { id:'P027', sku:'BEV-012', barcode:'DMO0027', name:'Verna Water 1.5L',          categoryId:'CAT-BEV', imagePath:'/demo/products/beverages.svg', costPricePence:350,   sellingPricePence:450,   openingQty:90, reorderPoint:25, vatRateBps:0,    unit:'bottle' },

  // ── DAIRY ─────────────────────────────────────────────────────────────────
  { id:'P028', sku:'DAI-001', barcode:'DMO0028', name:'Nestlé Ideal Milk 160g',    categoryId:'CAT-DAI', imagePath:'/demo/products/dairy.svg',     costPricePence:900,   sellingPricePence:1200,  openingQty:55, reorderPoint:15, vatRateBps:0,    unit:'tin'    },
  { id:'P029', sku:'DAI-002', barcode:'DMO0029', name:'Peak Milk Tin 400g',        categoryId:'CAT-DAI', imagePath:'/demo/products/dairy.svg',     costPricePence:2200,  sellingPricePence:2900,  openingQty:38, reorderPoint:10, vatRateBps:0,    unit:'tin'    },
  { id:'P030', sku:'DAI-003', barcode:'DMO0030', name:'Cowbell Sachet Box (40s)',  categoryId:'CAT-DAI', imagePath:'/demo/products/dairy.svg',     costPricePence:1200,  sellingPricePence:1600,  openingQty:28, reorderPoint:8,  vatRateBps:0,    unit:'box'    },
  { id:'P031', sku:'DAI-004', barcode:'DMO0031', name:'Yoyo Yogurt 500ml',         categoryId:'CAT-DAI', imagePath:'/demo/products/dairy.svg',     costPricePence:800,   sellingPricePence:1100,  openingQty:48, reorderPoint:12, vatRateBps:0,    unit:'cup'    },
  { id:'P032', sku:'DAI-005', barcode:'DMO0032', name:'Fanta Yogurt Drink 350ml',  categoryId:'CAT-DAI', imagePath:'/demo/products/dairy.svg',     costPricePence:300,   sellingPricePence:400,   openingQty:75, reorderPoint:20, vatRateBps:0,    unit:'bottle' },
  { id:'P033', sku:'DAI-006', barcode:'DMO0033', name:'Pinky Yogurt (bag)',        categoryId:'CAT-DAI', imagePath:'/demo/products/dairy.svg',     costPricePence:250,   sellingPricePence:350,   openingQty:90, reorderPoint:25, vatRateBps:0,    unit:'bag'    },
  { id:'P034', sku:'DAI-007', barcode:'DMO0034', name:'Butter 250g',               categoryId:'CAT-DAI', imagePath:'/demo/products/dairy.svg',     costPricePence:1600,  sellingPricePence:2100,  openingQty:22, reorderPoint:6,  vatRateBps:0,    unit:'pack'   },
  { id:'P035', sku:'DAI-008', barcode:'DMO0035', name:'Laughing Cow Cheese 200g',  categoryId:'CAT-DAI', imagePath:'/demo/products/dairy.svg',     costPricePence:2500,  sellingPricePence:3300,  openingQty:14, reorderPoint:4,  vatRateBps:0,    unit:'pack'   },
  { id:'P036', sku:'DAI-009', barcode:'DMO0036', name:'Fresh Eggs (tray of 30)',   categoryId:'CAT-DAI', imagePath:'/demo/products/dairy.svg',     costPricePence:3000,  sellingPricePence:3800,  openingQty:18, reorderPoint:5,  vatRateBps:0,    unit:'tray'   },
  { id:'P037', sku:'DAI-010', barcode:'DMO0037', name:'Blue Band Butter 500g',     categoryId:'CAT-DAI', imagePath:'/demo/products/dairy.svg',     costPricePence:2800,  sellingPricePence:3500,  openingQty:12, reorderPoint:3,  vatRateBps:0,    unit:'pack'   },

  // ── SNACKS ────────────────────────────────────────────────────────────────
  { id:'P038', sku:'SNK-001', barcode:'DMO0038', name:'Pringles Original 165g',    categoryId:'CAT-SNK', imagePath:'/demo/products/snacks.svg',    costPricePence:2500,  sellingPricePence:3200,  openingQty:22, reorderPoint:6,  vatRateBps:1500, unit:'can'    },
  { id:'P039', sku:'SNK-002', barcode:'DMO0039', name:'Lays Chips 40g',            categoryId:'CAT-SNK', imagePath:'/demo/products/snacks.svg',    costPricePence:600,   sellingPricePence:800,   openingQty:55, reorderPoint:15, vatRateBps:1500, unit:'bag'    },
  { id:'P040', sku:'SNK-003', barcode:'DMO0040', name:'Digestive Biscuits 250g',   categoryId:'CAT-SNK', imagePath:'/demo/products/snacks.svg',    costPricePence:900,   sellingPricePence:1200,  openingQty:48, reorderPoint:12, vatRateBps:1500, unit:'pack'   },
  { id:'P041', sku:'SNK-004', barcode:'DMO0041', name:'Cabin Biscuits 200g',       categoryId:'CAT-SNK', imagePath:'/demo/products/snacks.svg',    costPricePence:700,   sellingPricePence:950,   openingQty:55, reorderPoint:15, vatRateBps:0,    unit:'pack'   },
  { id:'P042', sku:'SNK-005', barcode:'DMO0042', name:'Tom Tom Candy (bag)',        categoryId:'CAT-SNK', imagePath:'/demo/products/snacks.svg',    costPricePence:300,   sellingPricePence:400,   openingQty:70, reorderPoint:20, vatRateBps:0,    unit:'bag'    },
  { id:'P043', sku:'SNK-006', barcode:'DMO0043', name:'Milo Choco Bar 22g',        categoryId:'CAT-SNK', imagePath:'/demo/products/snacks.svg',    costPricePence:150,   sellingPricePence:200,   openingQty:110,reorderPoint:30, vatRateBps:0,    unit:'bar'    },
  { id:'P044', sku:'SNK-007', barcode:'DMO0044', name:'Gala Sausage Roll',         categoryId:'CAT-SNK', imagePath:'/demo/products/snacks.svg',    costPricePence:350,   sellingPricePence:500,   openingQty:90, reorderPoint:25, vatRateBps:0,    unit:'roll'   },
  { id:'P045', sku:'SNK-008', barcode:'DMO0045', name:'Kit-Kat 2-Finger 20g',      categoryId:'CAT-SNK', imagePath:'/demo/products/snacks.svg',    costPricePence:500,   sellingPricePence:700,   openingQty:38, reorderPoint:10, vatRateBps:0,    unit:'bar'    },
  { id:'P046', sku:'SNK-009', barcode:'DMO0046', name:'Oreo Biscuits 137g',        categoryId:'CAT-SNK', imagePath:'/demo/products/snacks.svg',    costPricePence:1200,  sellingPricePence:1600,  openingQty:28, reorderPoint:8,  vatRateBps:1500, unit:'pack'   },
  { id:'P047', sku:'SNK-010', barcode:'DMO0047', name:'Honey Peanuts 200g',        categoryId:'CAT-SNK', imagePath:'/demo/products/snacks.svg',    costPricePence:700,   sellingPricePence:950,   openingQty:42, reorderPoint:12, vatRateBps:0,    unit:'bag'    },
  { id:'P048', sku:'SNK-011', barcode:'DMO0048', name:'Twix Bar 58g',              categoryId:'CAT-SNK', imagePath:'/demo/products/snacks.svg',    costPricePence:600,   sellingPricePence:800,   openingQty:28, reorderPoint:8,  vatRateBps:0,    unit:'bar'    },
  { id:'P049', sku:'SNK-012', barcode:'DMO0049', name:'Club Cream Crackers 200g',  categoryId:'CAT-SNK', imagePath:'/demo/products/snacks.svg',    costPricePence:800,   sellingPricePence:1050,  openingQty:38, reorderPoint:10, vatRateBps:0,    unit:'pack'   },

  // ── HOUSEHOLD ─────────────────────────────────────────────────────────────
  { id:'P050', sku:'HOU-001', barcode:'DMO0050', name:'Omo Detergent 500g',        categoryId:'CAT-HOU', imagePath:'/demo/products/household.svg', costPricePence:1200,  sellingPricePence:1600,  openingQty:48, reorderPoint:12, vatRateBps:1500, unit:'pack'   },
  { id:'P051', sku:'HOU-002', barcode:'DMO0051', name:'Ariel Detergent 1kg',       categoryId:'CAT-HOU', imagePath:'/demo/products/household.svg', costPricePence:2200,  sellingPricePence:2900,  openingQty:28, reorderPoint:8,  vatRateBps:1500, unit:'pack'   },
  { id:'P052', sku:'HOU-003', barcode:'DMO0052', name:'Sunlight Dishwash 500ml',   categoryId:'CAT-HOU', imagePath:'/demo/products/household.svg', costPricePence:900,   sellingPricePence:1200,  openingQty:48, reorderPoint:12, vatRateBps:1500, unit:'bottle' },
  { id:'P053', sku:'HOU-004', barcode:'DMO0053', name:'Parazone Bleach 1L',        categoryId:'CAT-HOU', imagePath:'/demo/products/household.svg', costPricePence:700,   sellingPricePence:950,   openingQty:38, reorderPoint:10, vatRateBps:1500, unit:'bottle' },
  { id:'P054', sku:'HOU-005', barcode:'DMO0054', name:'Dettol Multi-Surface 500ml',categoryId:'CAT-HOU', imagePath:'/demo/products/household.svg', costPricePence:1500,  sellingPricePence:2000,  openingQty:28, reorderPoint:8,  vatRateBps:1500, unit:'bottle' },
  { id:'P055', sku:'HOU-006', barcode:'DMO0055', name:'Local Broom',               categoryId:'CAT-HOU', imagePath:'/demo/products/household.svg', costPricePence:1200,  sellingPricePence:1600,  openingQty:14, reorderPoint:4,  vatRateBps:0,    unit:'each'   },
  { id:'P056', sku:'HOU-007', barcode:'DMO0056', name:'Sponge Scrubber (3-pack)',  categoryId:'CAT-HOU', imagePath:'/demo/products/household.svg', costPricePence:500,   sellingPricePence:700,   openingQty:28, reorderPoint:8,  vatRateBps:1500, unit:'pack'   },
  { id:'P057', sku:'HOU-008', barcode:'DMO0057', name:'Nylon Shopping Bags (pack)',categoryId:'CAT-HOU', imagePath:'/demo/products/household.svg', costPricePence:400,   sellingPricePence:600,   openingQty:38, reorderPoint:10, vatRateBps:0,    unit:'pack'   },
  { id:'P058', sku:'HOU-009', barcode:'DMO0058', name:'Mop Head Refill',           categoryId:'CAT-HOU', imagePath:'/demo/products/household.svg', costPricePence:2000,  sellingPricePence:2700,  openingQty:10, reorderPoint:3,  vatRateBps:1500, unit:'each'   },
  { id:'P059', sku:'HOU-010', barcode:'DMO0059', name:'Cockroach Spray 300ml',     categoryId:'CAT-HOU', imagePath:'/demo/products/household.svg', costPricePence:1300,  sellingPricePence:1750,  openingQty:18, reorderPoint:5,  vatRateBps:1500, unit:'can'    },

  // ── TOILETRIES ────────────────────────────────────────────────────────────
  { id:'P060', sku:'TOI-001', barcode:'DMO0060', name:'Dettol Soap 90g',           categoryId:'CAT-TOI', imagePath:'/demo/products/toiletries.svg',costPricePence:600,   sellingPricePence:800,   openingQty:75, reorderPoint:20, vatRateBps:1500, unit:'bar'    },
  { id:'P061', sku:'TOI-002', barcode:'DMO0061', name:'Rexona Deodorant 150ml',    categoryId:'CAT-TOI', imagePath:'/demo/products/toiletries.svg',costPricePence:1800,  sellingPricePence:2400,  openingQty:28, reorderPoint:8,  vatRateBps:1500, unit:'can'    },
  { id:'P062', sku:'TOI-003', barcode:'DMO0062', name:'Colgate Toothpaste 100ml',  categoryId:'CAT-TOI', imagePath:'/demo/products/toiletries.svg',costPricePence:1100,  sellingPricePence:1500,  openingQty:48, reorderPoint:12, vatRateBps:1500, unit:'tube'   },
  { id:'P063', sku:'TOI-004', barcode:'DMO0063', name:'Oral-B Toothbrush Medium',  categoryId:'CAT-TOI', imagePath:'/demo/products/toiletries.svg',costPricePence:700,   sellingPricePence:950,   openingQty:38, reorderPoint:10, vatRateBps:1500, unit:'each'   },
  { id:'P064', sku:'TOI-005', barcode:'DMO0064', name:'Dove Shampoo 200ml',        categoryId:'CAT-TOI', imagePath:'/demo/products/toiletries.svg',costPricePence:2800,  sellingPricePence:3600,  openingQty:18, reorderPoint:5,  vatRateBps:1500, unit:'bottle' },
  { id:'P065', sku:'TOI-006', barcode:'DMO0065', name:'Vaseline Body Lotion 400ml',categoryId:'CAT-TOI', imagePath:'/demo/products/toiletries.svg',costPricePence:2000,  sellingPricePence:2600,  openingQty:22, reorderPoint:6,  vatRateBps:1500, unit:'bottle' },
  { id:'P066', sku:'TOI-007', barcode:'DMO0066', name:'Nivea Body Lotion 200ml',   categoryId:'CAT-TOI', imagePath:'/demo/products/toiletries.svg',costPricePence:2200,  sellingPricePence:2900,  openingQty:18, reorderPoint:5,  vatRateBps:1500, unit:'bottle' },
  { id:'P067', sku:'TOI-008', barcode:'DMO0067', name:'Gillette Razor 2-pack',     categoryId:'CAT-TOI', imagePath:'/demo/products/toiletries.svg',costPricePence:500,   sellingPricePence:700,   openingQty:38, reorderPoint:10, vatRateBps:1500, unit:'pack'   },
  { id:'P068', sku:'TOI-009', barcode:'DMO0068', name:'Always Ultra Thin (8-pack)',categoryId:'CAT-TOI', imagePath:'/demo/products/toiletries.svg',costPricePence:1500,  sellingPricePence:2000,  openingQty:28, reorderPoint:8,  vatRateBps:0,    unit:'pack'   },
  { id:'P069', sku:'TOI-010', barcode:'DMO0069', name:'Cotton Buds 100-count',     categoryId:'CAT-TOI', imagePath:'/demo/products/toiletries.svg',costPricePence:500,   sellingPricePence:700,   openingQty:32, reorderPoint:10, vatRateBps:1500, unit:'pack'   },

  // ── BABY & HEALTH ─────────────────────────────────────────────────────────
  { id:'P070', sku:'BAB-001', barcode:'DMO0070', name:'Pampers Baby Dry S3 (24s)', categoryId:'CAT-BAB', imagePath:'/demo/products/baby-health.svg',costPricePence:6000,  sellingPricePence:7800,  openingQty:14, reorderPoint:4,  vatRateBps:0,    unit:'pack'   },
  { id:'P071', sku:'BAB-002', barcode:'DMO0071', name:'Huggies Newborn (24s)',     categoryId:'CAT-BAB', imagePath:'/demo/products/baby-health.svg',costPricePence:5500,  sellingPricePence:7200,  openingQty:10, reorderPoint:3,  vatRateBps:0,    unit:'pack'   },
  { id:'P072', sku:'BAB-003', barcode:'DMO0072', name:'Cerelac Wheat Honey 250g',  categoryId:'CAT-BAB', imagePath:'/demo/products/baby-health.svg',costPricePence:2800,  sellingPricePence:3600,  openingQty:18, reorderPoint:5,  vatRateBps:0,    unit:'tin'    },
  { id:'P073', sku:'BAB-004', barcode:'DMO0073', name:'NAN Pro Formula 400g',      categoryId:'CAT-BAB', imagePath:'/demo/products/baby-health.svg',costPricePence:5500,  sellingPricePence:7200,  openingQty:9,  reorderPoint:3,  vatRateBps:0,    unit:'tin'    },
  { id:'P074', sku:'BAB-005', barcode:'DMO0074', name:'Vitamin C 500mg (30-count)',categoryId:'CAT-BAB', imagePath:'/demo/products/baby-health.svg',costPricePence:1200,  sellingPricePence:1600,  openingQty:22, reorderPoint:6,  vatRateBps:0,    unit:'pack'   },
  { id:'P075', sku:'BAB-006', barcode:'DMO0075', name:'Paracetamol 500mg Strip',   categoryId:'CAT-BAB', imagePath:'/demo/products/baby-health.svg',costPricePence:300,   sellingPricePence:400,   openingQty:48, reorderPoint:15, vatRateBps:0,    unit:'strip'  },
  { id:'P076', sku:'BAB-007', barcode:'DMO0076', name:'ORS Sachets (10-pack)',     categoryId:'CAT-BAB', imagePath:'/demo/products/baby-health.svg',costPricePence:800,   sellingPricePence:1100,  openingQty:18, reorderPoint:5,  vatRateBps:0,    unit:'pack'   },
  { id:'P077', sku:'BAB-008', barcode:'DMO0077', name:'Strepsils (24-count)',      categoryId:'CAT-BAB', imagePath:'/demo/products/baby-health.svg',costPricePence:1500,  sellingPricePence:2000,  openingQty:14, reorderPoint:4,  vatRateBps:0,    unit:'pack'   },

  // ── FROZEN / CHILLED ──────────────────────────────────────────────────────
  { id:'P078', sku:'FRZ-001', barcode:'DMO0078', name:'Fan Ice Vanilla 2L',        categoryId:'CAT-FRZ', imagePath:'/demo/products/frozen.svg',    costPricePence:900,   sellingPricePence:1200,  openingQty:22, reorderPoint:6,  vatRateBps:0,    unit:'tub'    },
  { id:'P079', sku:'FRZ-002', barcode:'DMO0079', name:'Fan Choco Cone 500ml',      categoryId:'CAT-FRZ', imagePath:'/demo/products/frozen.svg',    costPricePence:350,   sellingPricePence:500,   openingQty:38, reorderPoint:10, vatRateBps:0,    unit:'cone'   },
  { id:'P080', sku:'FRZ-003', barcode:'DMO0080', name:'Mövenpick Vanilla 500ml',   categoryId:'CAT-FRZ', imagePath:'/demo/products/frozen.svg',    costPricePence:3500,  sellingPricePence:4600,  openingQty:8,  reorderPoint:2,  vatRateBps:1500, unit:'tub'    },
  { id:'P081', sku:'FRZ-004', barcode:'DMO0081', name:'Frozen Whole Chicken (kg)', categoryId:'CAT-FRZ', imagePath:'/demo/products/frozen.svg',    costPricePence:2200,  sellingPricePence:2900,  openingQty:14, reorderPoint:4,  vatRateBps:0,    unit:'kg'     },
  { id:'P082', sku:'FRZ-005', barcode:'DMO0082', name:'Tilapia Fish Frozen (kg)',  categoryId:'CAT-FRZ', imagePath:'/demo/products/frozen.svg',    costPricePence:3000,  sellingPricePence:3900,  openingQty:10, reorderPoint:3,  vatRateBps:0,    unit:'kg'     },
  { id:'P083', sku:'FRZ-006', barcode:'DMO0083', name:'Beef Sausages (6-pack)',    categoryId:'CAT-FRZ', imagePath:'/demo/products/frozen.svg',    costPricePence:1500,  sellingPricePence:2000,  openingQty:18, reorderPoint:5,  vatRateBps:0,    unit:'pack'   },
  { id:'P084', sku:'FRZ-007', barcode:'DMO0084', name:'Cheese Sausage Roll (Frozen)',categoryId:'CAT-FRZ',imagePath:'/demo/products/frozen.svg',   costPricePence:1200,  sellingPricePence:1600,  openingQty:14, reorderPoint:4,  vatRateBps:0,    unit:'pack'   },
  { id:'P085', sku:'FRZ-008', barcode:'DMO0085', name:'Ice Block 1kg',             categoryId:'CAT-FRZ', imagePath:'/demo/products/frozen.svg',    costPricePence:200,   sellingPricePence:300,   openingQty:48, reorderPoint:15, vatRateBps:0,    unit:'block'  },

  // ── LOCAL MARKET ──────────────────────────────────────────────────────────
  { id:'P086', sku:'LCL-001', barcode:'DMO0086', name:'Red Palm Oil 1L',           categoryId:'CAT-LCL', imagePath:'/demo/products/local-market.svg',costPricePence:1800, sellingPricePence:2300,  openingQty:28, reorderPoint:8,  vatRateBps:0,    unit:'bottle' },
  { id:'P087', sku:'LCL-002', barcode:'DMO0087', name:'Shea Butter 250g',          categoryId:'CAT-LCL', imagePath:'/demo/products/local-market.svg',costPricePence:1200, sellingPricePence:1600,  openingQty:18, reorderPoint:5,  vatRateBps:0,    unit:'jar'    },
  { id:'P088', sku:'LCL-003', barcode:'DMO0088', name:'Dried Pepper 100g',         categoryId:'CAT-LCL', imagePath:'/demo/products/local-market.svg',costPricePence:500,  sellingPricePence:700,   openingQty:38, reorderPoint:12, vatRateBps:0,    unit:'pack'   },
  { id:'P089', sku:'LCL-004', barcode:'DMO0089', name:'Dried Herrings 100g',       categoryId:'CAT-LCL', imagePath:'/demo/products/local-market.svg',costPricePence:600,  sellingPricePence:800,   openingQty:32, reorderPoint:10, vatRateBps:0,    unit:'pack'   },
  { id:'P090', sku:'LCL-005', barcode:'DMO0090', name:'Dawadawa Balls (pack)',      categoryId:'CAT-LCL', imagePath:'/demo/products/local-market.svg',costPricePence:300,  sellingPricePence:450,   openingQty:48, reorderPoint:14, vatRateBps:0,    unit:'pack'   },
  { id:'P091', sku:'LCL-006', barcode:'DMO0091', name:'Beeswax Candles (3-pack)',  categoryId:'CAT-LCL', imagePath:'/demo/products/local-market.svg',costPricePence:800,  sellingPricePence:1100,  openingQty:22, reorderPoint:6,  vatRateBps:0,    unit:'pack'   },
  { id:'P092', sku:'LCL-007', barcode:'DMO0092', name:'Kenkey Balls (5-pack)',     categoryId:'CAT-LCL', imagePath:'/demo/products/local-market.svg',costPricePence:1000, sellingPricePence:1400,  openingQty:18, reorderPoint:5,  vatRateBps:0,    unit:'pack'   },
  { id:'P093', sku:'LCL-008', barcode:'DMO0093', name:'Agbalumo Pack',             categoryId:'CAT-LCL', imagePath:'/demo/products/local-market.svg',costPricePence:1500, sellingPricePence:2000,  openingQty:14, reorderPoint:4,  vatRateBps:0,    unit:'pack'   },
  { id:'P094', sku:'LCL-009', barcode:'DMO0094', name:'Groundnut Paste 200g',      categoryId:'CAT-LCL', imagePath:'/demo/products/local-market.svg',costPricePence:900,  sellingPricePence:1200,  openingQty:28, reorderPoint:8,  vatRateBps:0,    unit:'jar'    },
  { id:'P095', sku:'LCL-010', barcode:'DMO0095', name:'Plantain Chips 150g',       categoryId:'CAT-LCL', imagePath:'/demo/products/local-market.svg',costPricePence:700,  sellingPricePence:950,   openingQty:32, reorderPoint:10, vatRateBps:0,    unit:'bag'    },

  // ── STATIONERY / OTHER ────────────────────────────────────────────────────
  { id:'P096', sku:'STA-001', barcode:'DMO0096', name:'Exercise Book 40pg',        categoryId:'CAT-STA', imagePath:'/demo/products/stationery.svg', costPricePence:300,  sellingPricePence:400,   openingQty:48, reorderPoint:16, vatRateBps:1500, unit:'each'   },
  { id:'P097', sku:'STA-002', barcode:'DMO0097', name:'Ballpoint Pens (10-box)',   categoryId:'CAT-STA', imagePath:'/demo/products/stationery.svg', costPricePence:500,  sellingPricePence:700,   openingQty:28, reorderPoint:8,  vatRateBps:1500, unit:'box'    },
  { id:'P098', sku:'STA-003', barcode:'DMO0098', name:'Sticky Notes A6',           categoryId:'CAT-STA', imagePath:'/demo/products/stationery.svg', costPricePence:600,  sellingPricePence:800,   openingQty:18, reorderPoint:6,  vatRateBps:1500, unit:'pack'   },
  { id:'P099', sku:'STA-004', barcode:'DMO0099', name:'A4 Envelopes (25-pack)',    categoryId:'CAT-STA', imagePath:'/demo/products/stationery.svg', costPricePence:800,  sellingPricePence:1100,  openingQty:14, reorderPoint:4,  vatRateBps:1500, unit:'pack'   },
  { id:'P100', sku:'STA-005', barcode:'DMO0100', name:'Scotch Tape 18mm×10m',      categoryId:'CAT-STA', imagePath:'/demo/products/stationery.svg', costPricePence:350,  sellingPricePence:500,   openingQty:22, reorderPoint:8,  vatRateBps:1500, unit:'roll'   },
];
