import { readFileSync } from 'node:fs';
import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it, vi } from 'vitest';
import TodayScreen from '@/components/reports/today/TodayScreen';
import { agreeingReportScope, isQuietToday, todayNextActions, todayPartialKinds, type TodaySnapshot } from '@/lib/reports/today/model';
import { stage3aExplore, stage3aLinks } from '@/lib/reports/today/stage3a-nav';
import { tradingReplacesSalesAnalytics } from '@/lib/reports/today/trading-parity';

vi.mock('next/navigation', () => ({
  useRouter: () => ({ refresh: () => undefined }),
}));

const CUSTOMER_COPY = [
  'See sales, returns, profit and your best-selling products for a period you choose.',
  'Compare sales over time and see the products, categories and busy hours driving performance.',
  'See how sales, confirmed payments, refunds and product sales changed between two equal periods.',
  'Track confirmed cash, MoMo, card and bank payments separately from sales.',
  'Review Mobile Money payments waiting for confirmation before they count as money received.',
  'Track collections still pending with the payment provider.',
  'Compare expected cash with counted cash and investigate any difference.',
  'Trace every stock increase and decrease to a sale, purchase, return, transfer or adjustment.',
  'Find products selling below cost or below your profit target.',
  'See products likely to run out and decide what to purchase next.',
  'See sales generated by products linked to each supplier—not what you owe them.',
  'Review unusual discounts, cash differences and other activity worth checking.',
];

const FORBIDDEN = [
  'This is not a new Activity design',
  'already available',
  'blueprint',
  'migration',
  'technical limitation',
];

function quiet(): TodaySnapshot {
  return {
    readCount: 0,
    salesTodayPence: 0,
    salesCount: 0,
    yesterdayPence: 0,
    days: [{ key: '2026-09-30', label: 'Wed', salesPence: 0 }],
    moneyReceivedPence: 0,
    methods: [],
    cashDifferencePence: null,
    comparison: null,
    branches: null,
    profit: { state: 'omitted', grossProfitPence: null },
    topProducts: [],
    attention: [],
  };
}

function screen(snapshot: TodaySnapshot, extras: Partial<Parameters<typeof TodayScreen>[0]> = {}) {
  return renderToStaticMarkup(
    <TodayScreen
      section="today"
      scopeLabel="Main Branch"
      dateLabel="Wednesday 30 September 2026 · Local time"
      zoneName="GMT"
      updatedLabel="12:00"
      readOnly={false}
      currency="GHS"
      storeId="store-1"
      links={[]}
      exploreLinks={stage3aExplore(new Set(['/reports/dashboard', '/reports/money-received', '/reports/stock-movements']), { showNetworkQueue: false })}
      nextActions={todayNextActions({ role: 'OWNER', readOnly: false })}
      salesHref={null}
      snapshot={snapshot}
      blocked={null}
      failed={false}
      {...extras}
    />,
  );
}

describe('Today empty and partial states', () => {
  it('shows guidance and no zero chart when the day is quiet', () => {
    const markup = screen(quiet());
    expect(isQuietToday(quiet())).toBe(true);
    expect(markup).toContain('No sales have been recorded for Main Branch today');
    expect(markup).toContain('Nothing is wrong');
    expect(markup).toContain('Open Sell');
    expect(markup).toContain('Add stock');
    expect(markup).toContain('Explore reports');
    expect(markup).toContain('Understand sales');
    expect(markup).not.toContain('Last seven dates');
    expect(markup).not.toContain('GH₵0.00');
    expect(markup).not.toContain('Getting ready');
  });

  it('keeps a day with sales and no receipts on the dashboard', () => {
    const snapshot = quiet();
    snapshot.salesTodayPence = 5000;
    snapshot.salesCount = 1;
    snapshot.days = [{ key: '2026-09-30', label: 'Wed', salesPence: 5000 }];
    expect(todayPartialKinds(snapshot)).toContain('sales-without-receipts');
    const markup = screen(snapshot);
    expect(markup).toContain('data-today-state="partial"');
    expect(markup).toContain('GH₵50.00');
    expect(markup).toContain('No confirmed payments yet today');
    expect(markup).not.toContain('No sales have been recorded');
  });

  it('does not lead with a zero sales figure when receipts exist', () => {
    const snapshot = quiet();
    snapshot.moneyReceivedPence = 8000;
    snapshot.methods = [{ method: 'CASH', label: 'Cash', amountPence: 8000 }];
    expect(todayPartialKinds(snapshot)).toContain('receipts-without-sales');
    const markup = screen(snapshot);
    expect(markup).toContain('No sales recorded yet today');
    expect(markup).toContain('GH₵80.00');
    expect(markup).not.toContain('GH₵0.00');
  });

  it('states a missing till, mix, history, cost and attention without inventing figures', () => {
    const snapshot = quiet();
    snapshot.salesCount = 1;
    snapshot.salesTodayPence = 1000;
    snapshot.days = [{ key: '2026-09-30', label: 'Wed', salesPence: 1000 }];
    snapshot.profit = { state: 'incomplete', grossProfitPence: null };
    const kinds = todayPartialKinds(snapshot);
    expect(kinds).toEqual(expect.arrayContaining(['no-closed-till', 'no-payment-mix', 'no-history', 'missing-costs', 'no-attention']));
    const markup = screen(snapshot);
    expect(markup).toContain('No till has been closed today');
    expect(markup).toContain('no payment mix');
    expect(markup).toContain('no-history');
    expect(markup).toContain('Profit is hidden because some product costs are missing.');
    expect(markup).toContain('Nothing needs attention right now.');
  });

  it('hides sell and stock actions from a read-only account', () => {
    const markup = screen(quiet(), {
      readOnly: true,
      nextActions: todayNextActions({ role: 'MANAGER', readOnly: true }),
    });
    expect(markup).not.toContain('Open Sell');
    expect(markup).not.toContain('Add stock');
    expect(markup).toContain('read-only');
  });
});

describe('Reports navigation, Activity and More', () => {
  it('keeps the section tabs in the page flow', () => {
    const markup = screen(quiet());
    expect(markup).toContain('data-reports-nav="contextual"');
    expect(markup).not.toContain('fixed');
    expect(markup).toContain('aria-label="More reports"');
  });

  it('uses customer descriptions and withholds internal language', () => {
    const allowed = new Set([
      '/reports/dashboard',
      '/reports/analytics',
      '/reports/business-movement',
      '/reports/money-received',
      '/reports/momo-confirmation',
      '/reports/cash-drawer',
      '/reports/stock-movements',
      '/reports/margins',
      '/reports/reorder-suggestions',
      '/reports/sales-by-supplier',
      '/reports/risk-monitor',
      '/reports/income-statement',
      '/reports/exports',
      '/reports/owner',
      '/reports/audit-log',
    ]);
    const activity = stage3aLinks('activity', allowed, { showNetworkQueue: true, tradingReplacesSalesAnalytics: false });
    const purposes = activity.map((link) => link.purpose);
    for (const line of CUSTOMER_COPY) expect(purposes).toContain(line);
    const markup = renderToStaticMarkup(
      <TodayScreen
        section="activity"
        scopeLabel="Main Branch"
        dateLabel="Wednesday 30 September 2026 · Local time"
        zoneName="GMT"
        updatedLabel=""
        readOnly={false}
        currency="GHS"
        storeId="store-1"
        links={activity}
        salesHref={null}
        snapshot={null}
        blocked={null}
        failed={false}
      />,
    );
    for (const phrase of FORBIDDEN) expect(markup).not.toContain(phrase);
    expect(markup).not.toContain('Download last week');
    expect(markup).toContain('Open');
  });

  it('shows Sales Analytics for Growth until Trading covers it, and never for Starter', () => {
    expect(tradingReplacesSalesAnalytics()).toBe(false);
    const growth = new Set(['/reports/dashboard', '/reports/analytics']);
    const starter = new Set(['/reports/dashboard']);
    expect(stage3aLinks('activity', growth, { tradingReplacesSalesAnalytics: false }).map((link) => link.href)).toContain('/reports/analytics');
    expect(stage3aLinks('activity', growth, { tradingReplacesSalesAnalytics: true }).map((link) => link.href)).not.toContain('/reports/analytics');
    expect(stage3aLinks('activity', starter, { tradingReplacesSalesAnalytics: false }).map((link) => link.href)).not.toContain('/reports/analytics');
  });

  it('groups More reports and keeps owner tools off a manager set', () => {
    const owner = stage3aLinks('more', new Set(['/reports/income-statement', '/reports/exports', '/reports/owner', '/reports/audit-log']));
    expect(owner.map((link) => link.group)).toEqual(['Statements', 'Downloads', 'Owner tools', 'Owner tools']);
    const manager = stage3aLinks('more', new Set(['/reports/income-statement', '/reports/exports']));
    expect(manager.map((link) => link.label)).toEqual(['Income statement', 'Downloads']);
    expect(manager.map((link) => link.label).join(' ')).not.toContain('Owner brief');
    const source = readFileSync('lib/reports/today/stage3a-nav.ts', 'utf8');
    expect(source).not.toContain("label: 'Download last week'");
    expect(source).not.toContain("href: '/reports/balance-sheet'");
  });
});

describe('Report scope agreement', () => {
  const owned = [{ id: 'a', name: 'Main Branch' }, { id: 'b', name: 'Kejetia' }];

  it('names the one store that was queried', () => {
    expect(agreeingReportScope({ plan: 'GROWTH', selected: 'a', queriedStoreIds: ['a'], ownedStores: owned }).label).toBe('Main Branch');
  });

  it('refuses a Growth consolidated label', () => {
    expect(() => agreeingReportScope({ plan: 'GROWTH', selected: 'ALL', queriedStoreIds: ['a', 'b'], ownedStores: owned })).toThrow(/label/);
  });

  it('labels Pro consolidation only when every owned store is queried', () => {
    const agreed = agreeingReportScope({ plan: 'PRO', selected: 'ALL', queriedStoreIds: ['a', 'b'], ownedStores: owned });
    expect(agreed.label).toBe('Consolidated — all branches');
    expect(agreed.storeIds).toEqual(['a', 'b']);
    expect(() => agreeingReportScope({ plan: 'PRO', selected: 'ALL', queriedStoreIds: ['a'], ownedStores: owned })).toThrow(/label/);
  });

  it('refuses a named branch whose query list is different', () => {
    expect(() => agreeingReportScope({ plan: 'PRO', selected: 'a', queriedStoreIds: ['b'], ownedStores: owned })).toThrow(/label/);
  });
});
