import type { NavIconKey } from '@/lib/navigation-config';

/**
 * Today is `/reports`. Activity and More reports are directories of routes
 * that already have their own screens. Withheld statements are never linked.
 *
 * Sales Analytics stays beside Trading until `tradingReplacesSalesAnalytics()`
 * is true. Weekly Digest is not linked. The weekly file action is not added here.
 */

export const STAGE_3A_WITHHELD_HREFS = [
  '/reports/balance-sheet',
  '/reports/cashflow',
  '/reports/cashflow-forecast',
  '/reports/weekly-digest',
] as const;

export type Stage3aSection = 'today' | 'activity' | 'more';

export type Stage3aGroup =
  | 'Reports'
  | 'Queues'
  | 'Ledgers and controls'
  | 'Statements'
  | 'Downloads'
  | 'Owner tools';

export type ExploreGroup = 'Understand sales' | 'Follow money' | 'Control stock' | 'Review statements';

export type Stage3aLink = {
  href: string;
  label: string;
  purpose: string;
  group: Stage3aGroup;
  iconKey: NavIconKey;
  explore?: ExploreGroup;
};

export type Stage3aLinkOptions = {
  /** True only when Trading already covers every entitled Sales Analytics capability. */
  tradingReplacesSalesAnalytics?: boolean;
  /** Mobile Money network queue. Hidden when the business has not turned MoMo on. */
  showNetworkQueue?: boolean;
};

const ACTIVITY_LINKS: Stage3aLink[] = [
  {
    href: '/reports/dashboard',
    label: 'Trading',
    purpose: 'See sales, returns, profit and your best-selling products for a period you choose.',
    group: 'Reports',
    iconKey: 'reports',
    explore: 'Understand sales',
  },
  {
    href: '/reports/analytics',
    label: 'Sales analytics',
    purpose: 'Compare sales over time and see the products, categories and busy hours driving performance.',
    group: 'Reports',
    iconKey: 'analytics',
    explore: 'Understand sales',
  },
  {
    href: '/reports/business-movement',
    label: 'Business movement',
    purpose: 'See how sales, confirmed payments, refunds and product sales changed between two equal periods.',
    group: 'Reports',
    iconKey: 'profit',
    explore: 'Understand sales',
  },
  {
    href: '/reports/money-received',
    label: 'Money received',
    purpose: 'Track confirmed cash, MoMo, card and bank payments separately from sales.',
    group: 'Reports',
    iconKey: 'payments',
    explore: 'Follow money',
  },
  {
    href: '/settings/online-store/analytics',
    label: 'Storefront',
    purpose: 'See visits and orders from your online shop.',
    group: 'Reports',
    iconKey: 'orders',
    explore: 'Understand sales',
  },
  {
    href: '/reports/momo-confirmation',
    label: 'MoMo to confirm',
    purpose: 'Review Mobile Money payments waiting for confirmation before they count as money received.',
    group: 'Queues',
    iconKey: 'reconciliation',
    explore: 'Follow money',
  },
  {
    href: '/payments/reconciliation',
    label: 'MoMo with the network',
    purpose: 'Track collections still pending with the payment provider.',
    group: 'Queues',
    iconKey: 'reconciliation',
    explore: 'Follow money',
  },
  {
    href: '/reports/cash-drawer',
    label: 'Cash drawer',
    purpose: 'Compare expected cash with counted cash and investigate any difference.',
    group: 'Ledgers and controls',
    iconKey: 'cashDrawer',
    explore: 'Follow money',
  },
  {
    href: '/reports/stock-movements',
    label: 'Stock movements',
    purpose: 'Trace every stock increase and decrease to a sale, purchase, return, transfer or adjustment.',
    group: 'Ledgers and controls',
    iconKey: 'stockMovements',
    explore: 'Control stock',
  },
  {
    href: '/reports/margins',
    label: 'Product margins',
    purpose: 'Find products selling below cost or below your profit target.',
    group: 'Ledgers and controls',
    iconKey: 'profit',
    explore: 'Control stock',
  },
  {
    href: '/reports/reorder-suggestions',
    label: 'Stock to reorder',
    purpose: 'See products likely to run out and decide what to purchase next.',
    group: 'Ledgers and controls',
    iconKey: 'reorder',
    explore: 'Control stock',
  },
  {
    href: '/reports/sales-by-supplier',
    label: 'Sales by linked supplier',
    purpose: 'See sales generated by products linked to each supplier—not what you owe them.',
    group: 'Ledgers and controls',
    iconKey: 'supplierSales',
    explore: 'Control stock',
  },
  {
    href: '/reports/risk-monitor',
    label: 'Control alerts',
    purpose: 'Review unusual discounts, cash differences and other activity worth checking.',
    group: 'Ledgers and controls',
    iconKey: 'risk',
    explore: 'Follow money',
  },
];

const MORE_LINKS: Stage3aLink[] = [
  {
    href: '/reports/income-statement',
    label: 'Income statement',
    purpose: 'Sales, costs, expenses and profit for the whole business, not separated by branch.',
    group: 'Statements',
    iconKey: 'incomeStatement',
    explore: 'Review statements',
  },
  {
    href: '/reports/exports',
    label: 'Downloads',
    purpose: 'Download CSV files for sales, purchases, stock and the till.',
    group: 'Downloads',
    iconKey: 'exports',
  },
  {
    href: '/reports/owner',
    label: 'Owner brief',
    purpose: 'A short owner view of how the whole business is trading.',
    group: 'Owner tools',
    iconKey: 'ownerBrief',
  },
  {
    href: '/reports/audit-log',
    label: 'Audit log',
    purpose: 'See who changed important records.',
    group: 'Owner tools',
    iconKey: 'audit',
  },
];

export const EXPLORE_GROUPS: ExploreGroup[] = [
  'Understand sales',
  'Follow money',
  'Control stock',
  'Review statements',
];

export function stage3aSection(value: string | undefined): Stage3aSection {
  if (value === 'activity') return 'activity';
  if (value === 'more') return 'more';
  return 'today';
}

const WITHHELD = new Set<string>(STAGE_3A_WITHHELD_HREFS);

/** These screens reject a branch id. A store query would be an invalid scope. */
const NO_STORE_SCOPE = new Set([
  '/reports/income-statement',
  '/reports/exports',
  '/reports/owner',
  '/reports/audit-log',
  '/settings/online-store/analytics',
]);

export function withStoreScope(href: string, storeId: string | null): string {
  if (!storeId) return href;
  const url = new URL(href, 'https://tillflow.local');
  if (NO_STORE_SCOPE.has(url.pathname)) return `${url.pathname}${url.search}`;
  url.searchParams.set('storeId', storeId);
  return `${url.pathname}${url.search}`;
}

function linkVisible(link: Stage3aLink, allowedHrefs: ReadonlySet<string>, options: Stage3aLinkOptions): boolean {
  if (WITHHELD.has(link.href)) return false;
  if (link.href === '/reports/analytics' && options.tradingReplacesSalesAnalytics) return false;
  if (link.href === '/payments/reconciliation') return options.showNetworkQueue === true;
  return allowedHrefs.has(link.href);
}

export function stage3aLinks(
  section: Stage3aSection,
  allowedHrefs: ReadonlySet<string>,
  options: Stage3aLinkOptions = {},
): Stage3aLink[] {
  if (section === 'today') return [];
  const source = section === 'activity' ? ACTIVITY_LINKS : MORE_LINKS;
  return source.filter((link) => linkVisible(link, allowedHrefs, options));
}

/** Compact destinations for a quiet Today. Not the full Activity or More list. */
export function stage3aExplore(
  allowedHrefs: ReadonlySet<string>,
  options: Stage3aLinkOptions = {},
): Stage3aLink[] {
  return [...ACTIVITY_LINKS, ...MORE_LINKS].filter((link) => link.explore && linkVisible(link, allowedHrefs, options));
}

export type ReportReturnPath = {
  href: string;
  section: 'activity' | 'more';
  title: string;
  backLabel: 'Back to Activity' | 'Back to More reports';
};

const WITHHELD_TITLES: Record<(typeof STAGE_3A_WITHHELD_HREFS)[number], string> = {
  '/reports/balance-sheet': 'Balance sheet',
  '/reports/cashflow': 'Cash-flow statement',
  '/reports/cashflow-forecast': 'Cash-flow forecast',
  '/reports/weekly-digest': 'Weekly digest',
};

/** Every Activity and More destination, used to prove a return path exists. */
export function reportReturnPaths(): ReportReturnPath[] {
  return [...ACTIVITY_LINKS, ...MORE_LINKS].map((link) => ({
    href: link.href,
    section: ACTIVITY_LINKS.some((item) => item.href === link.href) ? 'activity' : 'more',
    title: link.label,
    backLabel: ACTIVITY_LINKS.some((item) => item.href === link.href) ? 'Back to Activity' : 'Back to More reports',
  }));
}

export function returnPathFor(pathname: string): ReportReturnPath | { withheld: true; title: string; href: string } | null {
  const listed = reportReturnPaths().find((path) => path.href === pathname);
  if (listed) return listed;
  if (pathname in WITHHELD_TITLES) {
    const href = pathname as keyof typeof WITHHELD_TITLES;
    return { withheld: true, title: WITHHELD_TITLES[href], href };
  }
  return null;
}

/**
 * A return link may carry one owned store id. ALL, duplicates, blanks and
 * foreign ids are dropped so the destination resolves its own scope.
 */
export function safeReturnStoreId(search: string, ownedStoreIds: readonly string[]): string | null {
  const params = new URLSearchParams(search.startsWith('?') ? search.slice(1) : search);
  const values = params.getAll('storeId').map((value) => value.trim()).filter((value) => value.length > 0);
  if (values.length !== 1) return null;
  const id = values[0];
  if (id === 'ALL') return null;
  const matches = ownedStoreIds.filter((owned) => owned === id);
  return matches.length === 1 ? id : null;
}
