export type ManagedPlan = 'STARTER' | 'GROWTH' | 'PRO';

export type ManagedState = 'ACTIVE' | 'DUE_SOON' | 'GRACE' | 'STARTER_FALLBACK' | 'READ_ONLY' | 'TRIAL';

export type BusinessHealth = 'HEALTHY' | 'WATCH' | 'AT_RISK';

export type ManagedBusiness = {
  id: string;
  name: string;
  ownerName: string;
  ownerPhone: string;
  ownerEmail: string;
  assignedManager: string;
  plan: ManagedPlan;
  effectivePlan: ManagedPlan;
  state: ManagedState;
  billingCadence: 'MONTHLY' | 'ANNUAL';
  subscriptionStartAt?: string | null;
  signedUpAt: string;
  planSetAt: string;
  nextDueAt: string;
  lastPaymentAt: string | null;
  monthlyValue: number;
  outstandingAmount: number;
  health: BusinessHealth;
  needsReview: boolean;
  reviewedAt: string | null;
  reviewedBy: string | null;
  lastActivityAt: string;
  branches: number;
  notes: string;
};

export const managedBusinesses: ManagedBusiness[] = [
  {
    id: 'adom-mart',
    name: 'Adom Mart',
    ownerName: 'Abena Owusu',
    ownerPhone: '+233 24 555 1101',
    ownerEmail: 'abena@adommart.example',
    assignedManager: 'Kojo Mensah',
    plan: 'STARTER',
    effectivePlan: 'STARTER',
    state: 'ACTIVE',
    billingCadence: 'MONTHLY',
    signedUpAt: '2026-02-15',
    planSetAt: '2026-02-15',
    nextDueAt: '2026-04-25',
    lastPaymentAt: '2026-03-25',
    monthlyValue: 199,
    outstandingAmount: 0,
    health: 'HEALTHY',
    needsReview: false,
    reviewedAt: '2026-04-01 09:15',
    reviewedBy: 'Kojo Mensah',
    lastActivityAt: '2026-04-08 11:10',
    branches: 1,
    notes: 'Stable single-branch tenant. Low support load.',
  },
  {
    id: 'sunrise-provisions',
    name: 'Sunrise Provisions',
    ownerName: 'Yaw Antwi',
    ownerPhone: '+233 20 441 2208',
    ownerEmail: 'yaw@sunriseprovisions.example',
    assignedManager: 'Esi Quansah',
    plan: 'STARTER',
    effectivePlan: 'STARTER',
    state: 'DUE_SOON',
    billingCadence: 'MONTHLY',
    signedUpAt: '2026-03-01',
    planSetAt: '2026-03-01',
    nextDueAt: '2026-04-12',
    lastPaymentAt: '2026-03-12',
    monthlyValue: 199,
    outstandingAmount: 199,
    health: 'WATCH',
    needsReview: false,
    reviewedAt: '2026-04-02 10:10',
    reviewedBy: 'Esi Quansah',
    lastActivityAt: '2026-04-08 09:42',
    branches: 1,
    notes: 'Needs pre-due reminder. Owner prefers MoMo confirmation before noon.',
  },
  {
    id: 'harvest-square',
    name: 'Harvest Square',
    ownerName: 'Rita Boateng',
    ownerPhone: '+233 54 330 9921',
    ownerEmail: 'rita@harvestsquare.example',
    assignedManager: 'Kojo Mensah',
    plan: 'GROWTH',
    effectivePlan: 'GROWTH',
    state: 'ACTIVE',
    billingCadence: 'MONTHLY',
    signedUpAt: '2026-01-20',
    planSetAt: '2026-03-05',
    nextDueAt: '2026-04-18',
    lastPaymentAt: '2026-03-18',
    monthlyValue: 349,
    outstandingAmount: 0,
    health: 'HEALTHY',
    needsReview: false,
    reviewedAt: '2026-03-06 14:05',
    reviewedBy: 'Kojo Mensah',
    lastActivityAt: '2026-04-08 12:05',
    branches: 1,
    notes: 'Strong reporting usage. Candidate for annual billing pitch.',
  },
  {
    id: 'green-basket',
    name: 'Green Basket',
    ownerName: 'Nana Kusi',
    ownerPhone: '+233 27 994 7202',
    ownerEmail: 'nana@greenbasket.example',
    assignedManager: 'Esi Quansah',
    plan: 'GROWTH',
    effectivePlan: 'GROWTH',
    state: 'ACTIVE',
    billingCadence: 'MONTHLY',
    signedUpAt: '2026-02-09',
    planSetAt: '2026-02-09',
    nextDueAt: '2026-04-22',
    lastPaymentAt: '2026-03-22',
    monthlyValue: 349,
    outstandingAmount: 0,
    health: 'HEALTHY',
    needsReview: false,
    reviewedAt: '2026-02-12 16:30',
    reviewedBy: 'Esi Quansah',
    lastActivityAt: '2026-04-08 10:55',
    branches: 1,
    notes: 'Good fit. No commercial friction at the moment.',
  },
  {
    id: 'market-hub',
    name: 'Market Hub',
    ownerName: 'Felicia Asare',
    ownerPhone: '+233 55 210 4408',
    ownerEmail: 'felicia@markethub.example',
    assignedManager: 'Kofi Ansah',
    plan: 'GROWTH',
    effectivePlan: 'GROWTH',
    state: 'GRACE',
    billingCadence: 'MONTHLY',
    signedUpAt: '2026-01-11',
    planSetAt: '2026-01-11',
    nextDueAt: '2026-04-03',
    lastPaymentAt: '2026-03-03',
    monthlyValue: 349,
    outstandingAmount: 349,
    health: 'WATCH',
    needsReview: false,
    reviewedAt: '2026-01-15 11:25',
    reviewedBy: 'Kofi Ansah',
    lastActivityAt: '2026-04-08 08:36',
    branches: 1,
    notes: 'In Growth grace. Relationship owner needs same-day follow-up.',
  },
  {
    id: 'harbor-value',
    name: 'Harbor Value',
    ownerName: 'Stephen Manu',
    ownerPhone: '+233 24 199 2034',
    ownerEmail: 'stephen@harborvalue.example',
    assignedManager: 'Kofi Ansah',
    plan: 'GROWTH',
    effectivePlan: 'STARTER',
    state: 'STARTER_FALLBACK',
    billingCadence: 'MONTHLY',
    signedUpAt: '2025-12-18',
    planSetAt: '2026-01-04',
    nextDueAt: '2026-03-28',
    lastPaymentAt: '2026-02-28',
    monthlyValue: 349,
    outstandingAmount: 349,
    health: 'AT_RISK',
    needsReview: false,
    reviewedAt: '2026-01-10 13:40',
    reviewedBy: 'Kofi Ansah',
    lastActivityAt: '2026-04-07 18:11',
    branches: 1,
    notes: 'Fallback active. Escalate if not paid before lockout date.',
  },
  {
    id: 'orchid-retail',
    name: 'Orchid Retail',
    ownerName: 'Mary Appiah',
    ownerPhone: '+233 50 009 4120',
    ownerEmail: 'mary@orchidretail.example',
    assignedManager: 'Kojo Mensah',
    plan: 'GROWTH',
    effectivePlan: 'GROWTH',
    state: 'TRIAL',
    billingCadence: 'MONTHLY',
    signedUpAt: '2026-04-01',
    planSetAt: '2026-04-01',
    nextDueAt: '2026-04-15',
    lastPaymentAt: null,
    monthlyValue: 349,
    outstandingAmount: 0,
    health: 'HEALTHY',
    needsReview: false,
    reviewedAt: null,
    reviewedBy: null,
    lastActivityAt: '2026-04-08 12:33',
    branches: 1,
    notes: 'Trial business. Schedule commercial conversion call before trial end.',
  },
  {
    id: 'capstone-grocers',
    name: 'Capstone Grocers',
    ownerName: 'Daniel Ofori',
    ownerPhone: '+233 26 880 9302',
    ownerEmail: 'daniel@capstonegrocers.example',
    assignedManager: 'Esi Quansah',
    plan: 'GROWTH',
    effectivePlan: 'GROWTH',
    state: 'ACTIVE',
    billingCadence: 'ANNUAL',
    signedUpAt: '2025-11-04',
    planSetAt: '2026-01-02',
    nextDueAt: '2027-01-02',
    lastPaymentAt: '2026-01-02',
    monthlyValue: 291,
    outstandingAmount: 0,
    health: 'HEALTHY',
    needsReview: false,
    reviewedAt: '2026-01-04 09:00',
    reviewedBy: 'Esi Quansah',
    lastActivityAt: '2026-04-08 07:59',
    branches: 1,
    notes: 'Annual Growth account. Strong candidate for referral program.',
  },
  {
    id: 'royal-stores',
    name: 'Royal Stores',
    ownerName: 'Kwaku Addae',
    ownerPhone: '+233 24 901 4402',
    ownerEmail: 'kwaku@royalstores.example',
    assignedManager: 'Kofi Ansah',
    plan: 'PRO',
    effectivePlan: 'PRO',
    state: 'ACTIVE',
    billingCadence: 'MONTHLY',
    signedUpAt: '2026-01-08',
    planSetAt: '2026-02-12',
    nextDueAt: '2026-04-20',
    lastPaymentAt: '2026-03-20',
    monthlyValue: 699,
    outstandingAmount: 0,
    health: 'HEALTHY',
    needsReview: false,
    reviewedAt: '2026-02-13 15:20',
    reviewedBy: 'Kofi Ansah',
    lastActivityAt: '2026-04-08 12:12',
    branches: 4,
    notes: 'Primary Pro showcase account. Uses owner dashboard daily.',
  },
  {
    id: 'union-fairprice',
    name: 'Union Fairprice',
    ownerName: 'Josephine Tetteh',
    ownerPhone: '+233 27 717 6609',
    ownerEmail: 'josephine@unionfairprice.example',
    assignedManager: 'Esi Quansah',
    plan: 'PRO',
    effectivePlan: 'STARTER',
    state: 'READ_ONLY',
    billingCadence: 'MONTHLY',
    signedUpAt: '2025-10-26',
    planSetAt: '2026-01-15',
    nextDueAt: '2026-03-15',
    lastPaymentAt: '2026-02-15',
    monthlyValue: 699,
    outstandingAmount: 699,
    health: 'AT_RISK',
    needsReview: false,
    reviewedAt: '2026-01-16 08:55',
    reviewedBy: 'Esi Quansah',
    lastActivityAt: '2026-04-05 14:18',
    branches: 3,
    notes: 'Read-only after Pro grace and fallback ended. Needs executive contact.',
  },
];

export const planRates: Record<ManagedPlan, number> = {
  STARTER: 199,
  GROWTH: 349,
  PRO: 699,
};