ALTER TABLE "Business"
ADD COLUMN "plan" TEXT NOT NULL DEFAULT 'STARTER',
ADD COLUMN "planStatus" TEXT NOT NULL DEFAULT 'ACTIVE',
ADD COLUMN "trialEndsAt" TIMESTAMP(3),
ADD COLUMN "planSetAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "planChangedByUserId" TEXT,
ADD COLUMN "billingNotes" TEXT;

UPDATE "Business"
SET "plan" = CASE
  WHEN "mode" = 'ADVANCED' AND "storeMode" = 'MULTI_STORE' THEN 'PRO'
  WHEN "mode" = 'ADVANCED' THEN 'GROWTH'
  ELSE 'STARTER'
END
WHERE "plan" IS NULL OR "plan" = 'STARTER';